### ISSUE TITLE
Add support for hidden service version 3

### ISSUE THREAD

**Issue by zerap1m** [rahra/onioncat#15]
With hidden services version 3 available with enhanced security features, any plans to enable onioncat to be compatible with HS v3?

**Comment by rahra** [comment]
V3 hostnames carry about 280 bits of information which obviously do not directly fit into a 128 bit IPv6 address. Thus there is some kind of additional lookup mechanism required.
Since Onioncat was developed to also work with I2P (which is based on 256 bit hostnames) there is a simple lookup mechanism using /etc/hosts already implemented.

Using /etc/hosts is enabled with the option -H. But I'd like to admit that I did not test it with v3 hostnames, yet...
Give it a try, i'm looking forward to further comments and highly appreciate to push Onioncat forward to v3.

**Comment by rahra** [comment]
...there are some security-related implications...
I'll write an article and elaborate on that topic a little bit more. I'll publish it here, stay tuned.

Meanwhile, there's a conference talk of 2014 where I already picked up that topic, unfortunately in German: https://www.youtube.com/watch?v=Zj4hSx6cW80

**Comment by gh338** [comment]
Tried the -H variant with v3 onion name mapped in the hosts.
The problem is that the hosts entries are not resolved correctly according to tor log it states:

Jul 23 10:53:16.000 [warn] Service address "xxxxxxxxxd" has an invalid length. Expected 56 but got 10.

the d is the correct last letter here x are for scrubbing.

**Comment by gh338** [comment]
the d appears an all addresses that are contacted - so not sure if this is a bug actually

**Comment by rahra** [comment]
Ok, I'll have a look.

**Comment by gh338** [comment]
Steps to reproduce:

1. Created a Tor Onion Service V3
2. Calculated the ipv6 address with ocat and shortened onion hostname ( first 16 chars ).
3. Put both V3 destinations ( 56 characters ) in /etc/hosts on both sides
4. Started ocat on both sides with the shortened onion name.
5. Started ping 
6. Ocat logging shows that initially it picks up the hosts mapped onion device
7. The tor router however only gets the shortened address request with an ending 'd' so from there on it will of course fail to operate
8. I took a look at the code and I cannot pinpoint the location(s) where the Tor onion address is shortened/transformed or how exactly this done.

Thanks for taking a look at this - V3 would be very nice to have.

**Comment by rahra** [comment]
There was definitely a buffer size issue in the SOCKS handler. Did cost me half of the night ;)
It's fixed in the latest commit https://github.com/rahra/onioncat/commit/630f1bda9517b5ac5899ca02fa970f390849409f .
I tested this on three different hosts now, using HSv3 service.

If you have an (OC) server to which you connect to, I'd also suggest to add option `-U` on the server side. With this OC does not create a new backward circuit but re-uses the incoming one directly for back traffic. This actually eliminates the need for putting the hosts into `/etc/hosts` on the server side as long as you do not initiate connections from this server.

**Comment by gh338** [comment]
Rahra thanks for that !!!
I'll test the latest git checkout following your recent comment and report back.

Cheers

**Comment by gh338** [comment]
Would it be possible to have a separate hosts file in the tor config dir - so we don't mess around with OS core configuration files ?

**Comment by gh338** [comment]
Tested successfully on ubuntu 18.04 + 18.10 with all ipv6 host mappings on all hosts added via suggested method (16char shortened v3 onion).

Thank you so very much !!!

**Comment by rahra** [comment]
> Would it be possible to have a separate hosts file in the tor config dir - so we don't mess around with OS core configuration files ?

Currently this is hard-coded set to the system hosts file. But you can edit the variable `path_hosts_` in the file `ocathosts.c` line number 64. It points to NULL and is initialized at runtime. But you can statically initialize it with whatever you like. It will not be overwritten (if !NULL).
E.g. `static char *path_hosts_ = "/etc/tor/hosts.onioncat";`

**Comment by gh338** [comment]
Well make it an option like -hostfile if possible ?

**Comment by rahra** [comment]
Yes, I already have it on my todo list ;)

**Comment by rahra** [comment]
There's a new branch with commit 9ad2784d274d283d16859db7dacf03f19104cecf
It introduces option -g <hosts_path>.

**Comment by gh338** [comment]
Sweet - will test asap.

**Comment by rahra** [comment]
Merged into master branch with commit 9ad2784d274d283d16859db7dacf03f19104cecf .
