### ISSUE TITLE
destination ff02::2 unreachable

### ISSUE THREAD

**Issue by hrustbb2** [rahra/onioncat#3]
`destination ff02::2 unreachable`

this problem occurs on the raspbian

**Comment by rahra** [comment]
This is not specific to Raspbian. As soon as a new network interface is attached to a system, the OS kernel tries to find IPv6 routers on the new network and sends out packets. ff02::2 is defined to be the IPv6 multicast destination for all routers on a network.
Onioncat (being connected to the tun network interface) receives these packets but cannot deliver them because the Onioncat network is not capable of multicasting. Thus, it says "unreachable" and drops the packets.
So you can safely ignore it. It just tells you that some undeliverable packets where sent to Onioncat.
