### ISSUE TITLE
What are example use cases?

### ISSUE THREAD

**Issue by cm157** [rahra/onioncat#33]
I am obviously not that tech literate but i have always been really curious what this software is and how people might use it for privacy?

Can people give me examples ?

**Comment by rahra** [comment]
Basically it is a VPN adapter which works on top of Tor or I2P. Thus, you can create a VPN between several nodes (computers, servers, whatever) so that they can directly communicate to each other without using direct Internet connections.
The primary use-case is to hide from any kind of surveillance but still have a completely IP-transparent connection between systems.

**Comment by cm157** [comment]
So its like 
PC1 -- VPN Ingress --- Tor --- VPN Egress -- PC2 ?

**Comment by rahra** [comment]
Yes, exactly.
You can have more than just 2 PCs.

**Comment by rahra** [comment]
I close this since I think it is answered. Don't hesitate to reopen it again if there are further questions.
